name: Pull request
on:  
  pull_request:
    types: [opened, synchronize, edited]
jobs:
  title:
    name: Ensure that title uses gitmoji
    runs-on: ubuntu-latest
    steps:
      - uses: paralenz/actions/gitmoji@v1.1.0

  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: paralenz/actions/setup-node@v1.1.0

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: actions/checkout@v2
      - uses: paralenz/actions/setup-node@v1.1.0
      - name: Run jest
        run: yarn test